### ISSUE TITLE
Bug in overloaded WFAligner::alignEndsFree()

### ISSUE THREAD

**Issue by maxbbbb** [smarco/WFA2-lib#11]
`WFAligner::alignEndsFree()` based on `char*` (line 106 in WFAligner.cpp) seems to be correct, but the other method based on `std::string` (line 122 in WFAligner.cpp) returns `WFAligner::alignEnd2End()`, which is not correct.

Instead, it is supposed to return `WFAligner::alignEndsFree()` using `.c_str()`:
```
  return alignEndsFree(
      pattern.c_str(), pattern.length(), patternBeginFree, patternEndFree,
      text.c_str(), text.length(), textBeginFree, textEndFree);
```

**Comment by smarco** [comment]
Thanks for the report. 

You are right! Solved in branch `development` (soon to be merged into `main`).
