### ISSUE TITLE
Feature questions

### ISSUE THREAD

**Issue by rmhubley** [smarco/WFA2-lib#12]
Curious if you have plans to extend this to produce local alignments ( e.g. all HSPs above some score threshold ), and scoring matrices?

**Comment by ekg** [comment]
This could be possible, but given the way that WFA works, it might be
difficult to get local alignments that aren't relatively close to the
optimal alignment. You might pick up on alternative alignments through
repeats though.

**Comment by smarco** [comment]
Agreed. The extension of the WFA to optimal local alignment (like in Smith-Waterman) is not trivial. Notwithstanding, you could do as DAligner does to narrow down local alignments using ends-free alignments around some anchors or seeds (for instance). There are other similar approaches.

Extension to score matrices is perfectly doable. Nevetheless, it requires some technical effort to be implement efficiently. Not among my priorities. But if I get some free time and it is of interest, sure.

**Comment by rmhubley** [comment]
Thanks for your quick and thoughtful responses.
