### ISSUE TITLE
About using WFA as an alternative for sDTW

### ISSUE THREAD

**Issue by hasindu2008** [smarco/WFA2-lib#27]
This is a question out of curiosity, so I might be naive. I am wondering if it is possible to use WFA as an alternative to subsequence dynamic time warping algorithm. My use case is to align raw nanopore signals which are time-series current signals rather than discrete bases.

**Comment by ekg** [comment]
If the signals, both query and target, are encoded as sequences of
integers, then it should just work. You might need to change the bit width
of the alphabet.

**Comment by smarco** [comment]
It is not a naive question; other people have raised the same question/proposal as the problems share a lot of similarities. So, yes, your ticket/question is more than well motivated.
