### ISSUE TITLE
WFA2-lib commons.h bleeds C macros

### ISSUE THREAD

**Issue by pjotrp** [smarco/WFA2-lib#35]
By including wfa2-lib headers into vcflib (for the great vcfwave tool) we bleed in a set of macros that are defined, such as FORMAT, EOL and TAB. A library should not export these by default! See

See https://github.com/vcflib/vcflib/issues/359

Downstream I have the option of not including wfa2-lib in the vcflib headers, or explicitly undefining macros. Both not what we want. Can you create a version that does not bleed macros? I prefer an upstream solution :). And thanks again for a great library!

**Comment by smarco** [comment]
Sure, Pjotr. At once.

**Comment by pjotrp** [comment]
@smarco I can do a PR if you want.

**Comment by smarco** [comment]
If it is urgent, go for the PR. No problem.

**Comment by pjotrp** [comment]
OK, you can assign me. I have the test setup in vcflib ;)

**Comment by pjotrp** [comment]
Closed with https://github.com/smarco/WFA2-lib/pull/38
