### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by tillea** [smarco/WFA2-lib#40]
Hi,
since WFA2-lib is a new depencency of vcflib I intend to package WFA2-lib for Debian to be able to upgrade the vcflib Debian package to its latest version.  To do so it helps a lot if you would tag your releases to give us sensible chances to tell apart what are random development commits and what is user oriented production code.
Thanks a lot, Andreas.

**Comment by smarco** [comment]
Ok, if this repo is going that seriously, I will put it in shape. Tag v2.3 added. 

What else should we do? What good practices should we adhere to? 
Let me know, and I'll do my best to deliver.

Cheers,

**Comment by tillea** [comment]
Hi,

Am Tue, Jan 17, 2023 at 11:26:18AM -0800 schrieb Santiago Marco-Sola:
> Ok, if this repo is going that seriously, I will put it in shape. Tag v2.3 added. 

Cool, thanks a lot for the extremely quick response.

> What else should we do? What good practices should we adhere to? 
> Let me know, and I'll do my best to deliver.

A quite important thing would be a proper install target to install the
libs to /usr/lib/MULTIARCH/ and the header files to /usr/include.  IMHO
it would be cleaner if the headers would install to subdirectories of
    /usr/include/wfa2   (or some better name here)

The easiest way to approach all this is using a modern build system
like autoconf, cmake or meson (according to your personal preference).
This would usually ease the creation of shared and static libraries
in parallel (which is standard for Debian packages)

Hope this helps, Andreas.

**Comment by pjotrp** [comment]
@tillea we'll create a CMake build in the coming days.

**Comment by tillea** [comment]
Am Wed, Jan 18, 2023 at 07:16:44AM -0800 schrieb Pjotr Prins:
> @tillea we'll create a CMake build in the coming days.

Sounds very good.  Extra points if you create shared and static lib in
parallel.

**Comment by pjotrp** [comment]
@smarco I think we can do a new release after the latest PR.
