### ISSUE TITLE
Do D and I have inverted roles in CIGAR strings?

### ISSUE THREAD

**Issue by marcelm** [smarco/WFA2-lib#46]
Running `wfademo.cpp`, I noticed that the meaning of D and I in the CIGAR output seems to have been swapped from their usual meaning. Here’s an example taken from the README:
```
    PATTERN    AGCTA-GTGTCAATGGCTACT---TTTCAGGTCCT
               | ||| |||||  ||||||||   | |||||||||
    TEXT       AACTAAGTGTCGGTGGCTACTATATATCAGGTCCT
    ALIGNMENT  1M1X3M1I5M2X8M3I1M1X9M
```
The README states that *text* is equivalent to *reference* and *pattern* equivalent to *query* (which makes sense). If I take the above pattern to be a sequencing read and the text to be a genome reference, then the two gaps would be considered to be deletions, but they are encoded as `1I` and `3I`, respectively. Or should I think about this differently?

**Comment by smarco** [comment]
Hi, 

This I can answer right away. The WFA2lib follows the convention that describes how to transform the Pattern/Query into the Text/Database/Reference (as in classic pattern matching papers). However, the SAM CIGAR standard works the other way around (as the Reference is the important sequence). Beyond the discussion of which one is better (I think they are both ok), if you want CIGAR-style alignments, just swap pattern <-> text sequences when calling the WFA align function, and you will get all the Ds converted into Is (and vice-versa).

Let me know if that helps.

**Comment by marcelm** [comment]
Thanks! I see. Would you consider adding a comment to the README to make this clear for others as well?

Swapping pattern and text is of course the simplest fix for this, and it is what I’m using at the moment.

**Comment by smarco** [comment]
Sure (sorry for the delay). Please, have a look into `development` and let me know if that feels more clear.

Thanks,

**Comment by marcelm** [comment]
Thanks, that is clear enough!

**Comment by lczech** [comment]
Hey, 

just found this here after scratching my head about the same issue for a while now. I get that WFA is coming from a classical string algorithm background, and as such it makes sense to use terms such as pattern and text. However, as far as I can tell, the CIGAR format is specific to bioinformatics, and so offering a function for it that gives the I/D operations flipped compared to the convention is kinda counter intuitive. It means that users either have to use an unconventional order of input arguments (flip pattern and text), or have to flip I/D in the CIGAR via their own post-processing - both don't feel "right". Also, the documentation says that it is "SAM compliant", which in the current orientation, it is unfortunately not.

Would it not make sense to offer CIGARs in the expected orientation for their standard use case in genomics? For backwards compatibility maybe via a second function or default argument to the existing one that keeps existing code working as-is?

Cheers and so long
Lucas

**Comment by criniguez** [comment]
Hey Lucas,

Thanks for reaching out.

To address this exact issue, the repository already includes a dedicated function for this.

You can use `cigar_sprint_SAM_CIGAR`, which automatically handles the transformation from the internal WFA CIGAR format to the standard, SAM-compliant format. This way, you don't need to add your own post-processing or swap your input arguments.

Let me know if this works for you.

Best regards,
Cristian

**Comment by lczech** [comment]
Hi Cristian,

thanks for the quick reply! However, this is not quite what I had in mind. This gives a string of the CIGAR, instead of the 32-bit encoding. However, it still gives in insertions and deletions in the wrong orientation to what SAM expects.

For instance, 

```
Insertion: 
  query: ACGAACGT  
  ref:   ACGA-CGT

  cigar_sprint_SAM_CIGAR : 4=1D3=
  SAM-correct should be  : 4=1I3=
```

So in short, despite the function being called `SAM`, it is not SAM-compliant.

I'd rather work with the 32-bit encoding, but with the I/D in the orientation where an insertion is an insertion as compared to the reference. In other words, SAM wants "what operations do I need to apply to the _reference_ to get the _query_", while WFA2 does it the other way round. As said, flipping the order of the input strings seems like a hacky way to achieve this, and not a clean solution, as that is confusing as well.

Or am I missing something here?

Cheers and so long
Lucas

**Comment by smarco** [comment]
Hi Lucas,

I see your point. At this moment, we cannot change the internal WFA CIGAR representation, as that would break compatibility for existing users/tools. However, we can look into making cigar_compute_CIGAR SAM-compliant or adding a SAM-compliant variant for the next release.

What interface would work best for you: a new function, a flag/argument, or a separate conversion function from WFA CIGAR to SAM CIGAR? Let us know, so we can plan it for the next release.

Best,

**Comment by lczech** [comment]
Hi Santiago,

thank you! Sure, no breaking change needed here; an alternative function, or adding a flag would work fine, I think. A conversion function would add overhead, so maybe not the best (or at least not as the main path - might still be useful to have). 

Also, what do you think, 32-bit encoded or written-out string? I think the former might be better, as that can then use the existing cigar print functions to get the string, right?

If it helps, [here](https://github.com/lczech/spear/blob/7e6bd2ac717c587d32ad9d47b1c674f1fbfb2c2d/lib/spear/align/wfa2.cpp#L208) is my current implementation to flip I/D, if that helps :-) It also removes trailing indels (as I want the cigar stripped down to the actual query), so ignore that part.

Cheers and thanks again
Lucas

**Comment by criniguez** [comment]
Hi Lucas,

We just pushed a commit fixing this and properly inverting the D and I operations within the SAM funtions. Everything should work correctly without you having to resort to any hacky string-flipping workarounds.

Regarding the 32-bit encoding you prefer, cigar.c actually includes two functions for generating the SAM CIGAR:
- cigar_sprint_SAM_CIGAR (the string version) 
- cigar_get_CIGAR (the 32-bit encoded version)

Let me know if cigar_get_CIGAR works for you now, or if you need any additional functionality.

Best regards,
Cristian

**Comment by lczech** [comment]
Oh great, thank you, that was quick! 

But that is a breaking change now, isn't it? For me it's fine, because I'm actively working on using this now, but it might affect users that are already using the functions? Then again, it was kinda wrong before (not SAM-compliant), so maybe that was the right decision then to fix it - and it seems except in this issue, no one has had the problem before :-)

Cheers
Lucas

**Comment by smarco** [comment]
I think it makes sense to fix this function’s behavior. The previous behavior was incorrect, and this change should make it work as advertised.

Regarding existing users of the function, my guess is that most users already handle this bookkeeping on their end, so I don’t think this change is too concerning in practice.

In any case, many thanks for the report.
