### ISSUE TITLE
Some questions on the readme

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [smarco/WFA2-lib#5]
Hi! Great new readme with super nice visualizations, sweet! We have some similar ones for our own paper, but yours are nicer ;)

Some questions that I have:
- Could you clarify how exactly WFA2-lib differs from WFA? (Maybe the features list could include what is/is not in WFA.) The introduction lists what is supported by WFA2, but doesn't make it super clear that these were not in WFA1.
- Re. `A note for the fierce competitors`: I totally understand and agree with this. Would you mind sharing the way in which you would like your code to be benchmarked, and how not to do it?

I've been using
```
bin/align_benchmark -i {input} -a gap-affine-wfa --affine-penalties="0,1,0,1"
```
and just use snakemake to time the command on 10MB input files. Do you think this is accurate? It does include the file IO overhead, but we also include that for our own code. (We only run for sequences >=10000 currently, so file IO is not the bottleneck anyway.) We only compare exact global alignment with edit-distance costs, so I don't think there is any parameter tuning needed on the WFA side right?

I see you also ported the `align_benchmark` tool to WFA2. Is this ready to replace the WFA1 benchmark already and should I switch over?

**Comment by smarco** [comment]
Hi!

> Great new readme with super nice visualizations, sweet! We have some similar ones for our own paper, but yours are nicer ;)

Thanks. I'm still working on elaborating on some sections. But this kind of positive feedback is always appreciated; thanks.

> Could you clarify how exactly WFA2-lib differs from WFA? (Maybe the features list could include what is/is not in WFA.) The introduction lists what is supported by WFA2, but doesn't make it super clear that these were not in WFA1.

WFA only implemented gap-affine global alignment. It was the first step to prove that the whole WFA idea was sound.
WFA2-lib extends this idea to multiple distances (edit, indel, gap-linear, ...), ends-free alignment, low-memory modes, and more. WFA2-lib aims to be a more versatile library that can offer many more features than the initial WFA1.

> Re. A note for the fierce competitors: I totally understand and agree with this. Would you mind sharing the way in which you would like your code to be benchmarked, and how not to do it?

Just try to compare apples to apples and be fair in the evaluation.

> bin/align_benchmark -i {input} -a gap-affine-wfa --affine-penalties="0,1,0,1"

Here, it is to my understanding that you are trying to use edit-distance alignment. Then, use edit-distance WFA:
`./bin/align_benchmark -i {input} -a edit-wfa`
If you are just computing the distance/score, add:
`./bin/align_benchmark -i {input} -a edit-wfa --wfa-score-only`

> and just use snakemake to time the command on 10MB input files. Do you think this is accurate? It does include the file IO overhead, but we also include that for our own code. 

I think it is ok. In any case, the `align_benchmark` tool will give you overall time and WFA-alignment time separated.

> We only compare exact global alignment with edit-distance costs, so I don't think there is any parameter tuning needed on the WFA side right?

Indeed. Computing the exact edit-distance (no heuristics) has little room for tuning.

> I see you also ported the align_benchmark tool to WFA2. Is this ready to replace the WFA1 benchmark already and should I switch over?

Use WFA2 only. If you miss anything, let me know.

Cheers,
