### ISSUE TITLE
Tag versionin

### ISSUE THREAD

**Issue by tbrekalo** [smarco/WFA2-lib#50]
Hi! Would you mind creating a new release as of merging: https://github.com/smarco/WFA2-lib/pull/48 into master for safer CMake FetchContent integration that doesn't depend on master or commit hash? 

Thanks! Cheers. :)

**Comment by smarco** [comment]
Of course, [here](https://github.com/smarco/WFA2-lib/releases/tag/v2.3.3) you are.

Let me know if you need anything else.

Cheers,
