### ISSUE TITLE
VERSION file breaks vcflib build on Mac

### ISSUE THREAD

**Issue by adamnovak** [smarco/WFA2-lib#62]
I'm trying to build vcflib for Mac. vcflib now includes this library as a dependency, and if it isn't installed it points the build process at a vendored copy in a submodule.

It adds the repository root of that submodule to the compiler's include search path, so you can `#include <wavefront/wavefront_aligner.h>` or whatever.

However, the repository root contains a file named `VERSION`, and on my Mac at least, line 37 of the C++ standard library header `/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/cstddef` is:

```
#include <version>
```

Because Mac is case-insensitive, the WFA2-lib `VERSION` file ends up getting included by the standard library, instead of the standard library's `version` header file.

Please rename the `VERSION` file to something else (maybe `VERSION.txt`), or move the `wavefront` directory into another level of subdirectory (maybe `include` or `src`), so that `vcflib` can include from it without having this happen.

Alternately, `vcflib` could change its build process to install WFA2-lib into a directory somewhere and then build with it from there.

**Comment by smarco** [comment]
Thanks for PR, @adamnovak. Much appreciated.
