### ISSUE TITLE
Right score for score-only alignment?

### ISSUE THREAD

**Issue by haojingshao** [smarco/WFA2-lib#81]
Hi Smarco,
I'm testing the examples/basic.c to test the score-only alignment(_attributes.alignment_scope = compute_score;_).

In the output, I got two scores. 
Score1: alignment score (_wf_aligner->cigar.score_)
Score2:SCORE (RE)COMPUTED (_cigar_score_gap_affine(&wf_aligner->cigar,&attributes.affine_penalties_))

In normal full-cigar alignment mode, Score1 may equal to score2. But score2 is equal to the standard NW algorithm score.
In score-only mode, Score1 is available but not equal to standard NW algorithm score. Score2 is not available, possibly because this mode does not calculate cigar.

Is there a way to use score-only alignment mode to get the correct NW algorithm score?

Best regards,
Haojing

**Comment by smarco** [comment]
Hi,

Whether you get the score from `wf_aligner->cigar.score` or re-compute the score, the resulting score has to be the same (otherwise is a bug). Can you copy and paste the C-code example that reproduces the problem?

Thanks,

**Comment by haojingshao** [comment]
Thank you for your quick response. I solve this problem. My error code is in version V2.2. I get the same score when I use the newest version. :)
